FROM python:3.7.5-slim-buster

WORKDIR /
RUN apt-get update \
&&  apt-get install -y build-essential \
&&  pip install keystone==12.0.2 \
&&  dpkg -P build-essential \
&&  apt auto-remove -y \
&&  rm -rf /root/.cache \
&&  rm -rf /var/lib/apt/lists/* \
&&  pip freeze > /requirements.txt \
&&  pip install pipenv \
&&  pipenv lock \
&&  rm -rf /requirements.txt
