# We want an older version so we have vulnerabilities to evaluate
FROM debian:buster-20190812-slim

RUN apt-get update\
&&  mkdir -p /usr/share/man/man1 \
&&  apt-get install -y tomcat9 \
&&  rm -rf /var/lib/apt/lists/*
